source/nanoFramework.System.Net/Security/NetworkSecurity.cs, source/nanoFramework.System.Net/Security/SslStream.cs
- Remove SslVerification from method parameters. It's now exposed as property.
- Rework methods to replace X509 certificate collections to single instance.
- Rework methods to use parameters matching the .NET API.
- Rework calls to SslNative accordingly.
- No point on using a certificate collection on embedded devices for authentication. If not on the CA root certificate store, the usual use case is to use a single specific certificate to authenticate.
- The default authentication option was not to validate certificate, which is clearly, a bad practice.
- The new default behaviour is now to authenticate. The SslVerification property allow a developer to change that behaviour, if needed.
- API is now inline with the .NET one.
- SSL sample pack from sample repo running on a …
=> Rework SslStream API

source/nanoFramework.System.Net/Security/CertificateManager.cs, source/nanoFramework.System.Net/Security/NetworkSecurity.cs, source/nanoFramework.System.Net/Security/SslStream.cs, source/nanoFramework.System.Net/System.Net.nfproj
- Add CertificateManager class.
- Add methods that allow adding/updating a CA Root certificate bundle to the device certificate store.
- ❗️❗️ **Remove `UpdateCertificates` method from `SslStream`** ❗️❗️ (and respective call in SslNative).
- The existing implementation lacks proper management of a X509 "certificate store". The only available method close to this was `UpdateCertificates` which was part of `SslStream`. Clearly not suitable for a regular use case where a certificate must exist on the SLL context prior to creating an SslStream and call any authenticate method.
- Addresses an [issue](https://github.com/NETMF/netmf-interpreter/issues/251) and a _kind-of_ design flaw inherited from .NETMF .
- SSL sample from samples repo.
=> Add CertificateManager class

source/nanoFramework.System.Net/Sockets/NetworkStream.cs, source/nanoFramework.System.Net/Sockets/Socket.cs
- Add SocketType property to Socket. Filled in in constructor.
- TI SimpleLink get socket option doesn't implement this.
- This is required in NetworkStream constructor for secure stream. It's fundamental in order to have support for secure sockets. 
- The implementation is not "expensive" on any perspective and it brings minor savings in native code size.
=> Add SocketType property to Socket

source/nanoFramework.System.Net/Sockets/Socket.cs
- Have to set socket type on Accept().
- After #67 socket type property has to be set.
- According to Berkley sockets definitions, when processing `Accept()` on a socket the socket type can only be a stream socket. See [here](https://en.wikipedia.org/wiki/Berkeley_sockets#accept) and [here](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socket?view=netframework-4.7.2#remarks).
- HTTP sample.
=> Fix missing setting of socket type

source/nanoFramework.System.Net/Properties/AssemblyInfo.cs, source/nanoFramework.System.Net/Sockets/Socket.cs
- Add remote end point field to Socket.
- Bump native version to 1.0.7.0.
- TI SimpleLink API requires on some calls the details of the remote endpoint where the socket is connected to, therefore we need to store this when connecting.
=> Add remote end point field to Socket

source/nanoFramework.System.Net/IPAddress.cs, source/nanoFramework.System.Net/IPEndPoint.cs, source/nanoFramework.System.Net/Properties/AssemblyInfo.cs, source/nanoFramework.System.Net/SocketAddress.cs, source/nanoFramework.System.Net/Sockets/Socket.cs, source/nanoFramework.System.Net/Sockets/SocketsNative.cs
- Add AddressFamily property to IPEndpoint.
- Add snapshot method to IPEndpoint and IPAddress to assist copying objects.
- Add several new fields to IPAddress.
- Add AddressFamily property to IPAddress.
- Add new properties and methods to SocketAddress.
- Replace byte array argument from several calls in NativeSocket with EndPoint type.
- Add several new properties in Socket to accommodate non-blocking connect.
- Adjust Sockets code to new calls to native socket.
- Add code in several Sockets methods to save remote end point and check for connection.
- Add several code bits towards adding support for IPv6.
- Add attribute to hide fields from Debugger on several classes.
- Rename several fields to follow coding guidelines.
- Fix some typos and missing references in comments for …
=> Major rework on Sockets

source/nanoFramework.System.Net/Security/NetworkSecurity.cs
- Remove SSL3 and Default from SslProtocols.
- Also rename enum items to follow .NET names.
- Update comments for documentation.
- Addresses nanoFramework/Home#471.
=> Remove SSL3 and Default from SslProtocols

source/nanoFramework.System.Net/DNS.cs, source/nanoFramework.System.Net/IPAddress.cs, source/nanoFramework.System.Net/Properties/AssemblyInfo.cs, source/nanoFramework.System.Net/Sockets/Socket.cs, source/nanoFramework.System.Net/Sockets/SocketsNative.cs, source/version.json
- Fix calls to nativesockets that use bye[] in parameters. They should use EndPoint types.
- Rename parameters for consistency.
- Rework code on callers accordingly.
- Fix code in IPAddress constructor with byte[] parameter.
- Simplified GetHostEntry to use new IPAddress constructor from byte[].
- Bump version to 1.1.1.0-preview.
- Bump native version to 1.1.1.0.
- SSL sample pack.
=> Fix calls address parameters

source/nanoFramework.System.Net/Properties/AssemblyInfo.cs, source/nanoFramework.System.Net/System.Net.nfproj, source/nanoFramework.System.Net/X509Certificates/X509Certificate2.cs, source/version.json
- Add X509Certificate2 class.
- Bump native version to 100.1.2.0.
- Bump version to 1.2.0-preview.
- Closes nanoFramework/Home#540.
- SSL sample: able to parse certificate with private key, able to connect to server using client certificate.
=> Add X509Certificate2

source/nanoFramework.System.Net/Security/SslStream.cs, source/version.json
- Change sslProtocol parameter to follow .NET API.
- Fix AuthenticateAsServer implementation which weren't putting the server certificate in the correct parameter when calling the handler.
- Update/fix documentation comments.
- Improve code in native call handler.
- Bump version to 1.4.1-preview.
- Removes unnecessary use of collection because sslprotocols has enum Flags attribute and it's packed into an ORed parameter when calling native code.
- Addresses nanoframework/Home#520.
=> Update and fix Authenticate methods

source/nanoFramework.System.Net/Sockets/Socket.cs
The socket struct has two fields for endpoints, a local and a remote endpoint. These files have always been Null, so the get request to these fields always returned Null. This makes it impossible to use methods like SendTo() and ReceiveFrom().
Nevertheless, the send() and receive() methods worked correctly. But sometimes it is necessary to determine the IP and port address of a connected device.
The problem was that there were two endpoints defined and initialized with Null in the GetEndPoint() method. Only one of them got updated but then the other one was used as return value. I removed the first one and adjusted the return value.
This has been tested with a custom STM32F427 based MCU board with network interface. Both client and server modes have been used as test applications. …
=> Fix return value of GetEndpoint()

source/nanoFramework.System.Net/NetworkInformation/Wireless80211Configuration.cs, source/nanoFramework.System.Net/NetworkInformation/WirelessAPConfiguration.cs, source/version.json
- Rename none enums to disable.
- ORed enable flag with others that require the interface to be enabled.
- Improve comments for documentation.
- Bump version to 1.5.0-preview.
- Makes wireless options more understandable. 
- ORing the enable options reflects the real operation on the device.
=> Update Wireless ConfigurationOptions

source/nanoFramework.System.Net/NetworkInformation/Wireless80211Configuration.cs, source/nanoFramework.System.Net/NetworkInformation/WirelessAPConfiguration.cs
- Fix declaration of wireless config enums.
=> Fix declaration of wireless config enums

.gitignore, nanoFramework.System.Net/NetworkInformation/IPGlobalProperties.cs, nanoFramework.System.Net/NetworkInformation/NetworkInterface.cs, nanoFramework.System.Net/Properties/AssemblyInfo.cs, nanoFramework.System.Net/System.Net.nfproj, version.json
- Add GetIsNetworkAvailable to NetworkInformation.
- Add IPGlobalProperties class implementing GetUnicastAddresses.
- Bump AssemblyNativeVersion to 100.1.3.2.
- Add sonarlint rules to solution.
- Need to have better and readily access to network information like connection status and IP address availability.
=> Improvements in Network information

nanoFramework.System.Net/IPAddress.cs, nanoFramework.System.Net/IPEndPoint.cs, nanoFramework.System.Net/SocketAddress.cs
- Rename field.
- Remove attribute preventing the debugger from showing it.
- Make the value visible in debugging and become inline with the full .NET Framework.
=> Expose Address field in IPAddress

nanoFramework.System.Net/IPAddress.cs, nanoFramework.System.Net/NetworkInformation/NetworkInterface.cs, nanoFramework.System.Net/Properties/AssemblyInfo.cs
- Replace IPAddress.Parse with call to existing method.
- Replace IPAddress.ToString with native implementation.
- Replace NetworkInformation.IPv4AddressToString with native implementation.
- Bump AssemblyNativeVersion to 100.1.3.3.
- Remove duplicated methods in different classes.
- Replace execution expensive methods with efficient native implementations.
- Network sample.
=> Replace conversion with native implementations

nanoFramework.System.Net/Properties/AssemblyInfo.cs, nanoFramework.System.Net/Security/NetworkSecurity.cs, nanoFramework.System.Net/Security/SslStream.cs, version.json
- Update documentation comments to reflect this new possibility.
- Update calls to native interface.
- Bump versions.
- Allow developers to use internally stored certificate.
- SSL sample in samples repo.
=> Add UseStoredDeviceCertificate to SecureSocket

nanoFramework.System.Net/X509Certificates/X509Certificate2.cs, version.json
Adding X509Certificate2 Public and Private Key buffer access
- Needed for MQTT to connect with certificate
=> Adding X509Certificate2 Public and Private Key buffer access

nanoFramework.System.Net/NetworkInformation/WirelessAPStation.cs
It was incorrect.
N/A although this is a breaking change!
=> Fix spelling of MacAddress property

nanoFramework.System.Net/Sockets/NetworkStream.cs
- In `NetworkStream` constructor parameters descriptions was misplaced. Fixed it.
- Avoid confusion.
- It's my first PR. So I highly motivated to train on this little fixes how to do PR's right.
- Checked by eyes.
=> Parameter description misplacement

nanoFramework.System.Net/IPAddress.cs
Align byte constructor with .net 
Will leave current support for IPV6 as in future it will need to be implemented fully. 
Breaking change but shouldn't be used anywhere as not compliant with .Net
Tested constructor for Ipv4 and Ipv6 addresses
=> Fix byte constructor

nanoFramework.System.Net/IPAddress.cs
- Reverting #217.
- See nanoFramework/Home#928
=> Revert #217

azure-pipelines.yml, nanoFramework.System.Net/DNS.cs, nanoFramework.System.Net/IPAddress.cs, nanoFramework.System.Net/IPEndPoint.cs, nanoFramework.System.Net/SocketAddress.cs
- Add missing Equals and GetHashCode on several classes.
- Rework GetHostEntry to properly parse data from native call.
- Apply back fix from #217
- Fix several comments for documentation.
- Several fixes in code style.
- Improvements from analysers.
- Resolves nanoFramework/Home#928.
- Fixes nanoFramework/Home#929.
- Running Unit Tests locally on device.
=> Various fixes and improvements

nanoFramework.System.Net/NetworkHelper/NetworkHelper.cs
- Event is now instanciated on class constructor.
- Update code accordingly.
- Makes it possible to wait on the event before calling the setup methods.
=> NetworkReady event is now instanciated on constructor

Tests/SocketTests/SocketOptionsTests.cs, Tests/SocketTests/SocketTests.nfproj, nanoFramework.System.Net/Sockets/Socket.cs
- Rework GetSocketOption to correctly return correct type with several SocketOptionName.
- GetSocketOption can now return value for SocketOptionName.DontLinger.
- Rewrote some parts of the documentation to make it clearer.
- Add some unit tests for socket options.
- Addresses nanoFramework/Home#937.
- Unit tests and network sample.
=> Improvements in get/set socket options

nanoFramework.System.Net/NetworkHelper/NetworkHelperInternal.cs
This change only enables DHCP when not already enabled
Found that resetting DHCP during start up when DHCP was already enabled cause the getting of IP to be unreliable.
WHen testing Ethernet found the DHCP was changed at the same time as a DHCP was being handled and caused the GOT IP event to go missing which was needed to start the SNTP task.
Tested with updated (NetworkHelper) version of Network Client sample with Ethernet on ESP32
=> Only Enable DHCP if required

nanoFramework.System.Net/X509Certificates/X509Certificate.cs, nanoFramework.System.Net/X509Certificates/X509Certificate2.cs
- Add default parameter value for password (null). 
- Improve documentation comments.
- Now it's possible to create a certificate with just the certificate data and an unencrypted private key.
=> Improvements in X.509 constructors

nanoFramework.System.Net/Properties/AssemblyInfo.cs, nanoFramework.System.Net/X509Certificates/X509Certificate.cs, nanoFramework.System.Net/X509Certificates/X509Certificate2.cs, version.json
- Remove password parameter from X.509 constructors.
- Update code accordingly.
- Update comments and improve where needed.
- Bump AssemblyNativeVersion to 100.1.5.0
- Bump version to 1.9.0.
- MbedTLS is not able to decode X.509 certs with password. Only private keys. Same happens with Azure Netx Duo (our other secured network layer). So it doesn't make sense to keep offering a feature that we can't support. 
- Despite being a breaking change (from the API perspective) it's not anticipated to cause any major hiccups in existing deployments as it is working as it is now (anyone trying to use it would have already complained about it by now).
- TLS samples.
=> Remove password parameter from X.509 constructors

nanoFramework.System.Net/NetworkInformation/WirelessAPConfiguration.cs
Validating WirelessAPConfiguration.MaxConnections >= 1
This solves the problem of starting the access point with no connections available (and possibly freezing the device)
- Fixes nanoFramework/Home#1380
ChatGPT generated the code ;)
=> WirelessAPConfiguration.MaxConnections is now validated

nanoFramework.System.Net/DNS.cs, nanoFramework.System.Net/IPAddress.cs, nanoFramework.System.Net/NetworkInformation/NetworkInterface.cs, nanoFramework.System.Net/NetworkInformation/WirelessAPConfiguration.cs, nanoFramework.System.Net/Properties/AssemblyInfo.cs, nanoFramework.System.Net/SocketAddress.cs, nanoFramework.System.Net/Sockets/NetworkStream.cs, nanoFramework.System.Net/Sockets/Socket.cs
This change goes with the interpreter update for IDF 5.1.1
It updates the socket code to support working with IPV6 for support of OpenThread and for general use.
- Tested changes in IPAddress to support IPV6 format addresses for Parsing and Outputting addresses.
- Tested with some local UDP and TCPIP socket code
TODO 
- Add some test cases for IPV6
=> Update sockets to support IPV6

Tests/IPAddressTests/IPAddressTests.cs, Tests/IPAddressTests/IPAddressTests.nfproj, Tests/IPAddressTests/nano.runsettings, nanoFramework.System.Net/IPAddress.cs, nanoFramework.System.Net/NetworkInformation/NetworkInterface.cs, nanoFramework.System.Net/Properties/AssemblyInfo.cs
Added `==` and `!=` operator overloads
There is existing code that does not use the Equals method so this will fix that.
On device
=> Added `==` and `!=` operator overloads to `IpAddress` 

Tests/IPAddressTests/IPAddressTests.cs, nanoFramework.System.Net/IPAddress.cs
- Added a check that left and right are both null
- Added unit tests to validate equality checking of null
It was broken: https://github.com/nanoframework/System.Net/pull/310#issuecomment-1913534827
Unit tests
=> Fixing null checks in equality operators

nanoFramework.System.Net/NetworkInformation/Wireless80211Configuration.cs
Validation of the wireless configuration fails if either the SSID is 32 characters long or the password is 64 characters long. By definition, however, these may have these respective lengths.
**changes:**
- Throwing `ArgumentOutOfRangeException` only when the `SSID` length is greater than 32 characters.
- throwing `ArgumentOutOfRangeException` only when the `PASSWORD` is greater than 64 characters.
**Backed up on the native side here:**
https://github.com/nanoframework/nf-interpreter/blob/main/src/HAL/Include/nanoHAL_Network.h#L268
**and here:**
https://github.com/nanoframework/nf-interpreter/blob/main/src/HAL/Include/nanoHAL_Network.h#L271
I did not raise an issue.
**See the discussion:**
https://github.com/orgs/nanoframework/discussions/1594#discussioncomment-11946872
=> Fix check for max values inclusive for ssid and password
